version: '2'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'jenkins-jdk8-mvn-docker'
    ports:
      - '15000:8080'
      - '50000:50000'
    volumes:
      - './jenkins_data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    privileged: true
    restart: unless-stopped
